### ISSUE TITLE
500 error

### ISSUE THREAD

**Issue by DreesCamertijn** [vives-projectwerk-2-2020/back-end#3]
volg de instrukties in de readme
test eerst of http://localhost:3000/hello werkt als dat het geval is 
serf dan naar http://localhost:3000/sensor dit heft de de 500 error
deze kan je te zien krijgen in de termenal
Message: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'particula.sensors' doesn't exist

**Comment by sillevl** [comment]
In de migration heet je tabel `sensor`, in het model wordt verwezen naar `sensors`. Pas je migration aan.

https://github.com/vives-projectwerk-2-2020/back-end/blob/fccfe386c09c2d88c787cefef816ccb1dcae770f/db/migrations/20200304083953_sensor.php#L35

**Comment by sillevl** [comment]
PS in het vervolg ook melden op welke branch jouw probleem van toepassing is; want in master en develop is dit niet te reproduceren

**Comment by DreesCamertijn** [comment]
oke bedankt
